language: haskell

notifications:
  email: false

install: 
  - cabal install hspec
  - cabal install text

script:
  - (cd Day1 && runhaskell Day1.hs)
  - (cd Day2 && runhaskell Test.hs && runhaskell Day2.hs)