language: haskell

install: skip
script:
  - for d in Day*; do
      cd "$d"
      echo "Running ${d}"
      runhaskell "${d}.hs"
      if [ -f Test.hs ]; then
        runhaskell Test.hs
      fi
      cd ..
    done